version: '3'

services:
  database:
    container_name: nestwafprimer
    image: postgres:latest 
    ports: 
      - "5432:5432"    
    env_file:
      - waf.env
    volumes: 
      - /var/lib/postgresql/data